Ct 24 tela de login
Projeto-Adocao-Caosciente/adocao-caosciente-frontend pull request #11
Opened 2023-10-19 18:11 UTC by Vasini25

Elementos da tela de login inseridos
Ainda faltam formatações corretas, responsividade e conexão com o banco.

2023-10-19 18:28 UTC, Ryrden commented on src/presentation/pages/Login.tsx
> +            <h2 className='justify-center text-lg font-light flex gap-2'>
a pagina deve segui uma hierarquia semantica de html, aqui pode ser a tag <p> já q n se trata de um titulo de sessão ou da pagina.

2023-10-19 18:30 UTC, Ryrden commented on src/presentation/pages/Login.tsx
> +            Login
Tudo que for texto deve estar dentro de uma tag que representa texto, como esse Login representa o titulo da sessão, sreia bom colocar dentro de um H1

2023-10-19 18:31 UTC, Ryrden commented on src/presentation/assets/LinkIcon.tsx
> +export default function UploadIcon() {
Faltou renomear a função para LinkIcon

2023-10-19 18:31 UTC, Ryrden requested changes
solicitei algumas mudanças. O deploy não está funcionando q eu fiz umas mudanças, mas logo volta. 

Ta show, só ajeitar

2023-10-22 22:44 UTC, Ryrden commented on src/presentation/pages/Login.tsx
> +            Login
Tudo que for texto deve estar dentro de uma tag que representa texto, como esse Login representa o titulo da sessão, sreia bom colocar dentro de um H1
```suggestion
            <h1 className="text-3xl font-bold">Login</h1>
```

2023-10-22 22:48 UTC, Ryrden commented on src/presentation/pages/Login.tsx
> +            </h2>
a pagina deve segui uma hierarquia semantica de html, aqui pode ser a tag "p" já q n se trata de um titulo de sessão ou da pagina.

```suggestion
            <p className='text-base justify-center text-lg font-light flex gap-2'>
              Não tem conta?  
              <Link to={'/ong/cadastro'} className='text-primary flex felx-col gap-1'>
                Cadastre-se 
                <LinkIcon/>
              </Link>
            </p>
```

2023-10-22 22:48 UTC, Ryrden commented on src/presentation/pages/Login.tsx
> +        <main className="xs:mx-5 md:mx-20 lg:mx-72">
Substituir aqui pela nova estilização container

```suggestion
        <main className="container">
```

2023-10-22 22:50 UTC, Ryrden commented on src/presentation/assets/LinkIcon.tsx
> +export default function UploadIcon() {
Faltou renomear a função para LinkIcon

```suggestion
export default function LinkIcon() {
```

2023-10-23 02:05 UTC, moniely-barboza commented on src/presentation/pages/Login.tsx
> +      <Navbar />
Sim, remover Navbar e adicionar a logo
```suggestion
{/* TODO: Adicionar logo */}
```

2023-10-23 02:08 UTC, moniely-barboza commented on src/presentation/pages/Login.tsx
> +              <Link to={'/ong/cadastro'} className='text-primary flex felx-col gap-1'>
Deu erro como 'to'. Funciona com 'href'
Não precisa de 'flex-col'

```suggestion
              <Link href={'/ong/cadastro'} className='text-primary flex gap-1'>
```

2023-10-23 02:11 UTC, moniely-barboza requested changes
Ficou bom. Deixei alguns comentários e falta colocar todo o formulário em um card, como no protótipo.

2023-10-24 02:49 UTC, merged